"""Synthetic Voynichese as a null hypothesis."""

from __future__ import annotations

from ..analysis import StatBundle, stat_bundle
from ..baselines import SyntheticOptions, synthetic_voynichese
from ..util import table
from . import Plugin, PluginContext
from ._common import rng, save_text, words


def run(ctx: PluginContext) -> dict:
    output_words = words(ctx)
    options = SyntheticOptions(
        length=ctx.setting("length") or len(output_words),
        copy_probability=ctx.setting("copyProbability", 0.62),
        lookback=ctx.setting("lookback", 250),
        seed_words=ctx.setting("seedWords", 60),
        second_edit_probability=ctx.setting("secondEditProbability", 0.10),
        affix_edit_probability=ctx.setting("affixEditProbability", 0.85),
        affix_pool=ctx.setting("affixPool", 24),
    )
    generated = synthetic_voynichese(output_words, options, rng(ctx))
    # The first words of the output are the real seed words the generator
    # started from, so a sample has to skip past them to show anything the
    # model actually produced.
    invented = generated[options.seed_words :] or generated

    real = stat_bundle(output_words, "your transliteration")
    fake = stat_bundle(generated, "synthetic self-citation")
    rows = [real.row(), fake.row()]

    differences = _differences(real, fake)

    blocks = [
        "Synthetic Voynichese (Timm and Schinner self-citation model)",
        "=" * 60,
        "",
        table(rows, StatBundle.headers()),
        "",
        "Where the imitation differs most",
        "-" * 32,
        table(differences, ["measure", "your text", "synthetic", "difference", "relative"]),
        "",
        "Sample of generated text",
        "-" * 24,
        " ".join(invented[:40]),
        "",
        "What this model is\n"
        "------------------\n"
        "Pick a word you have already written, copy it, and change it slightly - swap a suffix,\n"
        "alter a character. Repeat. There is no grammar, no vocabulary and no message; the text is\n"
        "generated by nothing but self-imitation.\n\n"
        "Timm and Schinner showed that this reproduces a great deal of Voynichese: the word length\n"
        "distribution, Zipf behaviour, the low type/token ratio, the way similar words cluster. It\n"
        "gets roughly half way to the manuscript's conditional entropy as well.\n\n"
        "That makes it the hardest null hypothesis available. A statistic your mapping 'passes'\n"
        "which this text also passes is not evidence of language - it is evidence that both texts\n"
        "were produced by copying and modifying. Only the measures where your text and this one\n"
        "genuinely differ can carry an argument.",
    ]
    save_text(ctx, "synthetic.txt", "\n".join(blocks) + "\n", "your text against a self-citation null model")

    return {
        "options": {
            "length": options.length,
            "copy_probability": options.copy_probability,
            "lookback": options.lookback,
            "affix_edit_probability": options.affix_edit_probability,
        },
        "real": real.to_dict(),
        "synthetic": fake.to_dict(),
        "differences": differences,
        "sample": invented[:60],
    }


def _differences(real: StatBundle, fake: StatBundle) -> list:
    fields = [
        "h1",
        "h2",
        "mean_word_length",
        "ttr",
        "mattr",
        "hapax_ratio",
        "zipf_slope",
        "heaps_beta",
        "immediate_repeat_rate",
        "binomial_fit_error",
        "slot_conformance",
    ]
    rows = []
    for field in fields:
        a = getattr(real, field)
        b = getattr(fake, field)
        relative = abs(a - b) / abs(a) if a else 0.0
        rows.append([field, "%.4f" % a, "%.4f" % b, "%+.4f" % (b - a), "%.1f%%" % (relative * 100)])
    rows.sort(key=lambda r: -float(r[4].rstrip("%")))
    return rows


PLUGIN = Plugin(
    name="synthetic",
    title="Synthetic Voynichese null model",
    stage="baseline",
    category="baselines",
    summary="Generates meaningless text that imitates Voynichese, and compares it with yours.",
    help=(
        "The self-citation model of Timm and Schinner: every new word is an earlier word, copied\n"
        "and lightly modified. No grammar, no vocabulary, no message.\n\n"
        "It is startling how much of Voynichese this reproduces. Word lengths, Zipf's law, the\n"
        "small vocabulary, the tendency of similar words to appear near each other - all fall out\n"
        "of copy-and-modify alone. Which is exactly why it belongs here: it sets the bar that any\n"
        "claim about the manuscript's statistics has to clear.\n\n"
        "The output lists your text and the imitation side by side, ordered by how far apart they\n"
        "are. The measures at the top of that list are the only ones where your reading is saying\n"
        "something the null model does not."
    ),
    defaults={
        "length": 0,
        "copyProbability": 0.62,
        "lookback": 250,
        "seedWords": 60,
        "secondEditProbability": 0.10,
        "affixEditProbability": 0.85,
        "affixPool": 24,
    },
    settings_help={
        "length": "How many words to generate; 0 matches your text.",
        "copyProbability": "Chance of copying a word unchanged rather than modifying it.",
        "lookback": "How far back the generator may reach for a word to copy; 0 means anywhere.",
        "seedWords": "How many real words to start from.",
        "secondEditProbability": "Chance of applying a second modification.",
        "affixEditProbability": "How often a modification swaps a whole prefix or suffix.",
        "affixPool": "How many prefixes and suffixes to harvest from the source text.",
    },
    heavy=True,
    run=run,
)
